### ISSUE TITLE
Oxford and Paris can't be download in the original links

### ISSUE THREAD

**Issue by yuleung** [Ashespt/AdvBCT#1]
The download links for the Oxford Buildings dataset and Paris Buildings dataset and the Flickr 100k dataset images are no longer available from the https://www.robots.ox.ac.uk/~vgg/data/oxbuildings/ and https://www.robots.ox.ac.uk/~vgg/data/parisbuildings/. Can you provide a copy? Thanks!

**Comment by Ashespt** [comment]
Sorry for that. I'm not sure if it is appropriate to disseminate data without permission. Perhaps you can download them from other open-source website?
