### ISSUE TITLE
about dataset.

### ISSUE THREAD

**Issue by myoh97** [Ashespt/AdvBCT#3]
hi, thanks for your great work.

i'd like to do some experiments based on your work,
however, it seems the datasets, RParis and ROxford, are no longer available at
: http://cmp.felk.cvut.cz/revisitop/

could you share how can i download them?

**Comment by Ashespt** [comment]
Perhaps https://www.kaggle.com/datasets/skylord/oxbuildings works.

**Comment by myoh97** [comment]
Thanks for your quick reply. i'll check it.
